name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # https://github.com/actions/setup-node#supported-version-syntax
          node-version: "lts/*"
      - run: npm install --global pnpm
      - run: pnpm install

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pnpm test
